### ISSUE TITLE
Error `Can't resolve 'styled-components'`

### ISSUE THREAD

**Issue by kawano-020** [TakumiUemoto/yoku-test-a#1]
`npm install`した後に`npm run start`したら下記のエラーが表示され、動かない。

```
Can't resolve 'styled-components'
```

**Comment by TakumiUemoto** [comment]
1.　node_modulesを削除.       =>  ターミナルで　$ rm -rf node_modules　を実行
2.　Module not found: Error: Can't resolve 'styled-components' in '/Users/uemoto/yoku-　　test-a/src' のエラーを自分の環境でも確認できた
3. 　styled-componentsを再インストール       =>     npm install 'styled-components'を実行
4. 　package.json の "dependencies"に "styled-components": "^5.3.6", を追記
    *Reactアプリケーションが正しいパスを認識できていない為なのか？
6. 　エラーがなくったことを確認した
